import = [
    "~/.config/alacritty/themes/themes/rose-pine.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/bin/tmux" 
args = [ "new-session", "-A", "-D", "-s", "main" ]

[window]
padding.x = 10
padding.y = 10

decorations = "None"

opacity = 0.60
blur = true

startup_mode = "Maximized"

option_as_alt = "Both"

dynamic_title = true

[font]
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
size = 13
